import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { NProgressComponent } from '../components/NProgress';
import './globals.css';
import { Suspense } from 'react';
import Providers from '@/store/Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Suspense>
          <NProgressComponent />
        </Suspense>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
